### PR TITLE
Support querying a single entity

### PR DESCRIPTION
**Pull request by Ralith**
Still considering whether this is worth having.

### CODE REVIEW

**Comment by 1tgr** [comment]
Would be good to have this, just now I wrote a sequence of calls to `get(entity).unwrap()` for individual components.

**Comment by extrawurst** [comment]
hm thought there is something for that (see https://github.com/Ralith/hecs/issues/50#issuecomment-581072732):

> It's unlikely to matter for performance in practice, but [`World::entity`](https://docs.rs/hecs/0.2.7/hecs/struct.World.html#method.entity) provides that.

**Comment by 1tgr** [comment]
Agree that `World::entity` allows me to access a single entity, but I still have to issue multiple calls to `get` or `get_mut` afterward. With this `World::query_one` it's a one-liner regardless of the number of components involved.

I'm not so concerned about performance in this case as convenience... the `query_` methods nicely handle the component checks for me, and they extend to `with`, `without` and `Option<T>` for more complex cases.

**Comment by extrawurst** [comment]
Agreed, I think it would be a nice addition to have `query_one`

**Comment by Ralith** [comment]
Thanks for the feedback! I'll move this forward. My only reservation was reluctance to increase the API surface area without anyone having actually asked for it.

**Comment by Ralith** [comment]
Revised the API a bit for more consistency with `query`; in particular `with`/`without` work, the error cases can be distinguished, and there's one less layer of indirection. Any final feedback?

**Comment by 1tgr** [comment]
LGTM!

**Comment by Ralith** [comment]
Released in 0.2.11.

**Pull request merged**
