### PR TITLE
Refactor and expose query archetype access

### PR DESCRIPTION
**Pull request by Ralith**
CC @Ratysz. This needs review for semantic correctness which I'm too sleepy to give it at the moment.

### CODE REVIEW

**Comment by Ratysz** [comment]
```rust
#[test]
fn archetype_access() {
    let mut world = World::new();
    world.spawn(());
    world.spawn((0usize,));
    type NoComps<Q> = Without<usize, Q>;
    type OnlyUsize<Q> = With<usize, Q>;
    let mut archetypes = world.archetypes();

    let a = archetypes.next().unwrap();
    assert_eq!(a.access::<NoComps<()>>(), Some(Access::Iterate));
    assert_eq!(a.access::<OnlyUsize<()>>(), None);
    assert_eq!(a.access::<NoComps<Option<&usize>>>(), Some(Access::Iterate));

    let a = archetypes.next().unwrap();
    assert_eq!(a.access::<NoComps<()>>(), None);
    assert_eq!(a.access::<OnlyUsize<()>>(), Some(Access::Iterate));
    assert_eq!(a.access::<NoComps<Option<&usize>>>(), Some(Access::Iterate));
}
```
This fails on last assert, claiming it should be `None`. Should it?

**Comment by Ralith** [comment]
> This fails on last assert, claiming it should be None. Should it?

I'm not sure what you mean by "claiming it should be None", but as written, I'd expect that assert to fail because `Without<usize, Q>` will never access an archetype that contains a `usize` for any `Q`.

Note that this test is fragile because the order of `archetypes` is not guaranteed.

**Comment by Ratysz** [comment]
> Note that this test is fragile because the order of `archetypes` is not guaranteed.

I know; haven't focused on a more robust way of differentiating them yet. Should probably use the trivial asserts in a `match` instead.

Let me rewrite this, because after reading my prior comment I realised it says something completely different to what I actually meant. Commented-out assert fails here:

```rust
#[test]
fn archetype_access() {
    let mut world = World::new();
    world.spawn(());
    world.spawn((0usize,));
    type NoComps<Q> = Without<usize, Q>;
    type OnlyUsize<Q> = With<usize, Q>;
    let mut archetypes = world.archetypes();

    let a = archetypes.next().unwrap();
    assert_eq!(a.access::<NoComps<()>>(), Some(Access::Iterate))
    assert_eq!(a.access::<OnlyUsize<()>>(), None);
    //assert_eq!(a.access::<NoComps<Option<&usize>>>(), None);
    assert_eq!(a.access::<OnlyUsize<Option<&usize>>>(), None);

    let a = archetypes.next().unwrap();
    assert_eq!(a.access::<NoComps<()>>(), None);
    assert_eq!(a.access::<OnlyUsize<()>>(), Some(Access::Iterate));
    assert_eq!(a.access::<NoComps<Option<&usize>>>(), None);
    assert_eq!(a.access::<OnlyUsize<Option<&usize>>>(), Some(Access::Read));
}
```

**Comment by Ralith** [comment]
A robust test could construct a world that necessarily has exactly one archetype. You could also separately test the number of archetypes you get from a world with multiple (note that `archetypes` returns an `ExactSizeIterator`, which has a `len` method).

> assert_eq!(a.access::<NoComps<Option<&usize>>>(), None);

This assert should fail. `Without<usize, Option<&usize>>` will succeed vs. the empty archetype because the empty archetype does not contain a `usize`, therefore the outer clause is satisfied, and `Option<Q>` will `Iterate` archetypes that do not satisfy `Q`.

**Comment by Ralith** [comment]
On second thought, it's difficult to do interesting tests on worlds with only one archetype because every world has the empty archetype.

**Pull request merged**
