### PR TITLE
View::get_unchecked

### PR DESCRIPTION
**Pull request by Ralith**

### CODE REVIEW

**Comment by adamreichold** [comment]
Hhhmmm, is this really required with `(Prepared)View::get` existing? Or put differently, is it possible to use this soundly where neither `View::get` nor `View::get_mut` would work?

**Comment by Ralith** [comment]
`View::get` cannot be used with queries that yield mutable references, so this is necessary to support cases where you want concurrent multiple access to two different entities from the same query.

**Comment by adamreichold** [comment]
Ah, indeed the references for distinct entities will not overlap. Thanks for explaining! I wonder whether this could be given a safe interface by e.g. passing in `[Entity; N]` and yielding `[Option<QueryItem<'q, Q>>; N]` now that const generics are stable? I guess checking `[Entity; N]` for duplicates would probably end-up `O(N^2)` without additional storage though?

**Comment by Ralith** [comment]
This came up in https://github.com/Ralith/hecs/issues/217. I'm open to the idea; this PR was just the minimum to avoid a regression from the deprecated column API.

**Pull request merged**
