### PR TITLE
Relicense from Apache 2 to Apache 2 OR MIT

### PR DESCRIPTION
**Pull request by Ralith**
We should relicense to be more consistent, and compatible, with the rest of the ecosystem. This requires consent from every contributor. To agree to relicensing, respond with:

> I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

Consent needed:
- [x] Google LLC
- [x] @mjhostet
- [x] @cedric-h
- [x] @Veykril
- [x] @sdleffler
- [x] @Winsalot
- [x] @AngelOfSol

### CODE REVIEW

**Comment by sdleffler** [comment]
Sounds great, I'm in. Consider this my proof of consent.

**Comment by Veykril** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by sdleffler** [comment]
Oops, I skimmed and missed the "respond with" bit. Just for completion's sake:

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by cedric-h** [comment]
approved

**Comment by AngelOfSol** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by mjhostet** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to chose either at their option.

**Comment by Ralith** [comment]
@Winsalot has not responded, and the email associated with his commit is bouncing messages, so I have removed examples/ffa_simulation.rs, which contains the full scope of his contributions. Hopefully he'll see this someday and we can restore it.

**Comment by Winsalot** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Ralith** [comment]
Thanks to everyone for taking the time to respond!

**Pull request merged**
